services:
  - type: web
    name: kosodate-line-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - fromGroup: line-gemini-keys

envVarGroups:
  - name: line-gemini-keys
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false